services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: TaskPass123
      POSTGRES_DB: tasktrackerdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./TaskTracker.Api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=db;Port=5432;Database=tasktrackerdb;Username=taskuser;Password=TaskPass123
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    environment:
      VITE_API_URL: http://localhost:8080/graphql
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  pgdata:
